### ISSUE TITLE
Is there a way to not resize the image if the size is smaller than the target size?

### ISSUE THREAD

**Issue by skayablars** [pqina/filepond-plugin-image-resize#1]
The documentation of the imageResizeMode property declares that

> All three settings will upscale images when there are smaller than the given target dimensions.

Is there a way to avoid this? I want to resize the image if the file is larger than the target dimensions but those images will contain a lot of text and it will be difficult to read if are upscaled.

**Comment by rikschennink** [comment]
There currently is not, I'll put it on the to-do list, shouldn't be to difficult to add.

**Comment by rikschennink** [comment]
Just pushed version `1.1.0` of both the `image-transform` and `image-resize` plugin.

Set `imageResizeUpscale` to `false` to prevent upscaling of images.

**Comment by skayablars** [comment]
@rikschennink  thank you :), awesome library and super support 💯
