### ISSUE TITLE
Resize according to a file size

### ISSUE THREAD

**Issue by d-damien** [pqina/filepond-plugin-image-resize#11]
Hi, I'm wondering if it could target a "file size" instead of an "image size" while downsizing images. I'm not sure how it is done, but this plugin for example has it :

- https://github.com/Donaldcwl/browser-image-compression
- demo : https://donaldcwl.github.io/browser-image-compression/example/basic.html

I believe this is worthy of such a complete plugin as Filepond.

**Comment by rikschennink** [comment]
Thanks for the request. I do struggle a bit to determine the use case for this? 

I imagine the server has a max upload size, but to respect that max size couldn't you calculate the max size a JPEG would be at a certain resolution & compression?

**Comment by d-damien** [comment]
You're right idk what I was thinking.

The remaining unknown is the metadata. I think it should be relevant to have a boolean to dropAllMetadata in the metadata plugin, unless that's what `fileMetadataObject: {}` already does.

**Comment by rikschennink** [comment]
What should `dropAllMetadata` do?

**Comment by d-damien** [comment]
Remove all metadata, except probably the ICC color profile. I am yet to see files with huge metadata, but I guess if they are out there, files could be refused by the server for being above max size, despite having been resized under the max dimensions.

**Comment by rikschennink** [comment]
The resize plugin can be used with the transform plugin, you can then set `imageTransformOutputStripImageHead` to `true` and it'll remove metadata
https://pqina.nl/filepond/docs/api/plugins/image-transform/
