### ISSUE TITLE
Multi Resizing

### ISSUE THREAD

**Issue by Dechowmedia** [pqina/filepond-plugin-image-resize#2]
Hey,

I tried scouring the documentation for a way to do multiple image sizes (lets say multiple sizing versions) - this is due to the need to make multiple images from one for better mobile optimization.

Is that possible or do the plugin only allow for one value set being provided? :)

Best,
Lucas

**Comment by rikschennink** [comment]
I think this is what you're looking for:
https://dev.to/pqina/generating-image-thumbnails-in-the-browser-using-javascript-and-filepond-10b8

**Comment by Dechowmedia** [comment]
Thank you so much for linking that resource :) - the documentation was good, but I was so in doubt about this, maybe it could be helped if the plugins' documentation could link for this specific use-case?

Anyways thanks for your help :) - closing the issue
